apiVersion: v1
kind: Service
metadata:
  name: mission-service
spec:
  selector:
    app: mission
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30036
  type: NodePort